[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "is_fib"
path = "src/is_fib/main.rs"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f128 = "0.2.9"